IBID/Models/ErrorViewModel.cs
namespace IBID.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

IBID/Models/ProdutoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace IBID.Models
{
    public class ProdutoModel
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Digite o nome!")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Digite o valor do Preco!")]
        public string Preco { get; set; }

        [Required(ErrorMessage = "Digite a Data De Cadastro!")]
        public DateTime DataDeCadastro { get; set; } = DateTime.Now;
    }
}

IBID/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using IBID.Models;

namespace IBID.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

IBID/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IBID.DataContext;
using IBID.Models;
using Microsoft.AspNetCore.Mvc;

namespace IBID.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly AppDbContext _context;

        public ProdutoController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var ListaDeProdutos = _context.Produtos.ToList();
            return View(ListaDeProdutos);
        }

        public IActionResult Criar()
        {
            return View();
        }

        
        public IActionResult Editar(int id)
        {
            var IDProduto = _context.Produtos.Find(id);

            if(IDProduto == null)
                    return NotFound();

            return View(IDProduto);
        }

        public IActionResult Deletar(int id)
        {
            var IDProduto = _context.Produtos.Find(id);

            if(IDProduto == null)
                    return NotFound();

            return View(IDProduto);
        }

        public IActionResult Detalhes(int id)
        {
            var IDProduto = _context.Produtos.Find(id);

            if(IDProduto == null)
                    return NotFound();

            return View(IDProduto);
        }
        
        [HttpPost]
        public IActionResult Criar(ProdutoModel model)
        {
            model.DataDeCadastro.ToString();
            try
            {
                if(model == null || model.DataDeCadastro > DateTime.Now || !ModelState.IsValid)
                {  
                    return View();
                }

                

                _context.Produtos.Add(model);
                _context.SaveChanges();

                TempData["MensagemSucesso"] = "Criação realizada com sucesso!";

                return RedirectToAction(nameof(Index));

            }catch(Exception x)
            {
                ViewData["error"] = "Ocorreu um erro ao criar o produto.";
                return View(model);
            }
        }

        [HttpPost]
        public IActionResult Editar(ProdutoModel model)
        {

            var ProdutoBanco = _context.Produtos.Find(model.Id);

            if(model.Id == null || model.Id == 0 || !ModelState.IsValid)
            {
                return View();
            }

            ProdutoBanco.Nome = model.Nome;
            ProdutoBanco.Preco = model.Preco;
            ProdutoBanco.DataDeCadastro = model.DataDeCadastro;

            _context.Produtos.Update(ProdutoBanco);
            _context.SaveChanges();

            TempData["MensagemSucesso"] = "Edição realizada com sucesso!";


            return RedirectToAction(nameof(Index));

        }

        [HttpPost]
        public IActionResult Deletar(ProdutoModel model){

            if(model.Id == null || model.Id == 0)
            {
                return View();
            }

            var ProdutoBanco = _context.Produtos.Find(model.Id);

            _context.Produtos.Remove(ProdutoBanco);
            _context.SaveChanges();

            TempData["MensagemSucesso"] = "Remoção realizada com sucesso!";


            return RedirectToAction(nameof(Index));
        }


        }  
    }

IBID/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

IBID/Views/Produto/Criar.cshtml
@model IBID.Models.ProdutoModel

@{
    ViewData["Title"] = "Criar novo Produto";
}

<h1>Criar novo Produto da IBID</h1>

<hr>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Criar">
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                 <span class="text-danger" asp-validation-for="Nome" ></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span class="text-danger" asp-validation-for="Preco" ></span>
            </div>
           <div class="form-group">
                <label asp-for="DataDeCadastro" class="control-label"></label>
                <input asp-for="DataDeCadastro" type="datetime-local" class="form-control" />
                 <span class="text-danger" asp-validation-for="DataDeCadastro" ></span>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<hr>
<br>
<div>
    <a asp-action="Index" class="btn btn-secondary"><i class="bi bi-arrow-90deg-left"></i> Voltar</a>
</div>

IBID/Views/Produto/Deletar.cshtml
@model IBID.Models.ProdutoModel

@{
    ViewData["Title"] = "Deletar Produto";
}

<h3 style="color: red;">Deseja realmente deletar esse Produto? essa operação é inrreversível</h3>

<hr>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Nome)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Nome)
        </dt>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Preco)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Preco)
        </dt>
        
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.DataDeCadastro)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.DataDeCadastro)
        </dt>
    </dl>
</div>

<br>

<form asp-action="Deletar">
    <input type="submit" value="Deletar" class="btn btn-danger"/>
</form>

<br>

<a asp-action="Index" class="btn btn-secondary"><i class="bi bi-arrow-90deg-left"></i> Voltar</a>

IBID/Views/Produto/Detalhes.cshtml
@model IBID.Models.ProdutoModel

@{
    ViewData["Title"] = "Detalhes do Produto";
}

<h3 style="color: red;">Seu Produto</h3>

<hr>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Nome)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Nome)
        </dt>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.Preco)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.Preco)
        </dt>
        
        <dt class="col-sm-2">
            @Html.DisplayNameFor(x => x.DataDeCadastro)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayFor(x => x.DataDeCadastro)
        </dt>
    </dl>
</div>

<br>

<a asp-action="Editar" asp-route-id="@Model.Id" class="btn btn-warning"><i class="bi bi-pencil-square"></i> Editar</a> 

<br>
<br>

<a asp-action="Index" class="btn btn-secondary"><i class="bi bi-arrow-90deg-left"></i> Voltar</a>

IBID/Views/Produto/Editar.cshtml
@model IBID.Models.ProdutoModel

@{
    ViewData["Title"] = "Editar novo Produto";
}

<h1>Editar novo Produto da IBID</h1>

<hr>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Editar">
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span class="text-danger" asp-validation-for="Nome" ></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span class="text-danger" asp-validation-for="Preco" ></span>
            </div>
           <div class="form-group">
                <label asp-for="DataDeCadastro" class="control-label"></label>
                <input asp-for="DataDeCadastro" type="datetime-local" class="form-control" />
                <span class="text-danger" asp-validation-for="DataDeCadastro" ></span>
            </div>
            <br>
            <div class="form-group">
                <input type="submit" value="Editar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<hr>
<br>
<div>
    <a asp-action="Index" class="btn btn-secondary"><i class="bi bi-arrow-90deg-left"></i> Voltar</a>
</div>

IBID/Views/Produto/Index.cshtml
@model IEnumerable<IBID.Models.ProdutoModel>


<h1>Seus produtos</h1>

<br>

<a asp-action="Criar" class="btn btn-success"><i class="bi bi-file-earmark-plus"></i> Criar Produto da IBID</a>

<br>

<br>

<br>

   
     @if(TempData["MensagemSucesso"] != null){
        <div class="alert alert-success text-light" role="alert">
          @TempData["MensagemSucesso"]
        </div>
    }
<br>

@{
    ViewData["Title"] = "Produtos criados";
}
<br>

   <table id="Produtos"  class="table table-light table-hover mt-5">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Preco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataDeCadastro)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(model => item.Preco)
                </td>
                <td>
                    @Html.DisplayFor(model => item.DataDeCadastro)
                </td>
                <td>
                    <a asp-action="Editar" asp-route-id="@item.Id" class="btn btn-warning"><i class="bi bi-pencil-square"></i> Editar</a> |
                    <a asp-action="Detalhes" asp-route-id="@item.Id" class="btn btn-primary"><i class="bi bi-zoom-in"></i> Detalhes</a> |
                    <a asp-action="Deletar" asp-route-id="@item.Id" class="btn btn-danger"><i class="bi bi-trash3-fill"></i> Deletar</a> 
                </td>
            </tr>
        }
    </tbody>
</table> 
    
   

IBID/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IBID</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Materia.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IBID.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IBID</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produtos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>